import type { FontWeightName } from "@/model/types";

// The same 14 families and supported weights as the original editor.
export const fontAssets: Record<string, number> = {
  "Playfair Display:regular": require("@expo-google-fonts/playfair-display/400Regular/PlayfairDisplay_400Regular.ttf"),
  "Playfair Display:medium": require("@expo-google-fonts/playfair-display/500Medium/PlayfairDisplay_500Medium.ttf"),
  "Playfair Display:semibold": require("@expo-google-fonts/playfair-display/600SemiBold/PlayfairDisplay_600SemiBold.ttf"),
  "Playfair Display:bold": require("@expo-google-fonts/playfair-display/700Bold/PlayfairDisplay_700Bold.ttf"),
  "Fraunces:regular": require("@expo-google-fonts/fraunces/400Regular/Fraunces_400Regular.ttf"),
  "Fraunces:medium": require("@expo-google-fonts/fraunces/500Medium/Fraunces_500Medium.ttf"),
  "Fraunces:semibold": require("@expo-google-fonts/fraunces/600SemiBold/Fraunces_600SemiBold.ttf"),
  "Fraunces:bold": require("@expo-google-fonts/fraunces/700Bold/Fraunces_700Bold.ttf"),
  "EB Garamond:regular": require("@expo-google-fonts/eb-garamond/400Regular/EBGaramond_400Regular.ttf"),
  "EB Garamond:medium": require("@expo-google-fonts/eb-garamond/500Medium/EBGaramond_500Medium.ttf"),
  "EB Garamond:semibold": require("@expo-google-fonts/eb-garamond/600SemiBold/EBGaramond_600SemiBold.ttf"),
  "EB Garamond:bold": require("@expo-google-fonts/eb-garamond/700Bold/EBGaramond_700Bold.ttf"),
  "Libre Baskerville:regular": require("@expo-google-fonts/libre-baskerville/400Regular/LibreBaskerville_400Regular.ttf"),
  "Libre Baskerville:medium": require("@expo-google-fonts/libre-baskerville/500Medium/LibreBaskerville_500Medium.ttf"),
  "Libre Baskerville:semibold": require("@expo-google-fonts/libre-baskerville/600SemiBold/LibreBaskerville_600SemiBold.ttf"),
  "Libre Baskerville:bold": require("@expo-google-fonts/libre-baskerville/700Bold/LibreBaskerville_700Bold.ttf"),
  "Merriweather:regular": require("@expo-google-fonts/merriweather/400Regular/Merriweather_400Regular.ttf"),
  "Merriweather:medium": require("@expo-google-fonts/merriweather/500Medium/Merriweather_500Medium.ttf"),
  "Merriweather:semibold": require("@expo-google-fonts/merriweather/600SemiBold/Merriweather_600SemiBold.ttf"),
  "Merriweather:bold": require("@expo-google-fonts/merriweather/700Bold/Merriweather_700Bold.ttf"),
  "Source Serif 4:regular": require("@expo-google-fonts/source-serif-4/400Regular/SourceSerif4_400Regular.ttf"),
  "Source Serif 4:medium": require("@expo-google-fonts/source-serif-4/500Medium/SourceSerif4_500Medium.ttf"),
  "Source Serif 4:semibold": require("@expo-google-fonts/source-serif-4/600SemiBold/SourceSerif4_600SemiBold.ttf"),
  "Source Serif 4:bold": require("@expo-google-fonts/source-serif-4/700Bold/SourceSerif4_700Bold.ttf"),
  "Instrument Serif:regular": require("@expo-google-fonts/instrument-serif/400Regular/InstrumentSerif_400Regular.ttf"),
  "Source Sans 3:regular": require("@expo-google-fonts/source-sans-3/400Regular/SourceSans3_400Regular.ttf"),
  "Source Sans 3:medium": require("@expo-google-fonts/source-sans-3/500Medium/SourceSans3_500Medium.ttf"),
  "Source Sans 3:semibold": require("@expo-google-fonts/source-sans-3/600SemiBold/SourceSans3_600SemiBold.ttf"),
  "Source Sans 3:bold": require("@expo-google-fonts/source-sans-3/700Bold/SourceSans3_700Bold.ttf"),
  "Nunito:regular": require("@expo-google-fonts/nunito/400Regular/Nunito_400Regular.ttf"),
  "Nunito:medium": require("@expo-google-fonts/nunito/500Medium/Nunito_500Medium.ttf"),
  "Nunito:semibold": require("@expo-google-fonts/nunito/600SemiBold/Nunito_600SemiBold.ttf"),
  "Nunito:bold": require("@expo-google-fonts/nunito/700Bold/Nunito_700Bold.ttf"),
  "Josefin Sans:regular": require("@expo-google-fonts/josefin-sans/400Regular/JosefinSans_400Regular.ttf"),
  "Josefin Sans:medium": require("@expo-google-fonts/josefin-sans/500Medium/JosefinSans_500Medium.ttf"),
  "Josefin Sans:semibold": require("@expo-google-fonts/josefin-sans/600SemiBold/JosefinSans_600SemiBold.ttf"),
  "Josefin Sans:bold": require("@expo-google-fonts/josefin-sans/700Bold/JosefinSans_700Bold.ttf"),
  "Space Grotesk:regular": require("@expo-google-fonts/space-grotesk/400Regular/SpaceGrotesk_400Regular.ttf"),
  "Space Grotesk:medium": require("@expo-google-fonts/space-grotesk/500Medium/SpaceGrotesk_500Medium.ttf"),
  "Space Grotesk:semibold": require("@expo-google-fonts/space-grotesk/600SemiBold/SpaceGrotesk_600SemiBold.ttf"),
  "Space Grotesk:bold": require("@expo-google-fonts/space-grotesk/700Bold/SpaceGrotesk_700Bold.ttf"),
  "Barlow Condensed:regular": require("@expo-google-fonts/barlow-condensed/400Regular/BarlowCondensed_400Regular.ttf"),
  "Barlow Condensed:medium": require("@expo-google-fonts/barlow-condensed/500Medium/BarlowCondensed_500Medium.ttf"),
  "Barlow Condensed:semibold": require("@expo-google-fonts/barlow-condensed/600SemiBold/BarlowCondensed_600SemiBold.ttf"),
  "Barlow Condensed:bold": require("@expo-google-fonts/barlow-condensed/700Bold/BarlowCondensed_700Bold.ttf"),
  "Atkinson Hyperlegible:regular": require("@expo-google-fonts/atkinson-hyperlegible/400Regular/AtkinsonHyperlegible_400Regular.ttf"),
  "Atkinson Hyperlegible:bold": require("@expo-google-fonts/atkinson-hyperlegible/700Bold/AtkinsonHyperlegible_700Bold.ttf"),
  "IBM Plex Mono:regular": require("@expo-google-fonts/ibm-plex-mono/400Regular/IBMPlexMono_400Regular.ttf"),
  "IBM Plex Mono:medium": require("@expo-google-fonts/ibm-plex-mono/500Medium/IBMPlexMono_500Medium.ttf"),
  "IBM Plex Mono:semibold": require("@expo-google-fonts/ibm-plex-mono/600SemiBold/IBMPlexMono_600SemiBold.ttf"),
  "IBM Plex Mono:bold": require("@expo-google-fonts/ibm-plex-mono/700Bold/IBMPlexMono_700Bold.ttf"),
};

export function nativeFont(family: string, weight: FontWeightName): string {
  const key = `${family}:${weight}`;
  return fontAssets[key] ? key : `${family}:regular`;
}
